# Generated by Django 3.1 on 2021-10-16 18:22

import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj', models.CharField(default=core.models.increment_project_number, max_length=20)),
            ],
            options={
                'order_with_respect_to': 'proj',
            },
        ),
        migrations.CreateModel(
            name='realdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_data', models.FileField(blank=True, upload_to='documents/%Y/%m/%d', validators=[core.validators.validate_file_extension])),
                ('name', models.CharField(max_length=20)),
                ('proj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'order_with_respect_to': 'real_data',
            },
        ),
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField()),
                ('training_cycles', models.IntegerField()),
                ('name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modeldata')),
            ],
        ),
        migrations.AddField(
            model_name='modeldata',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='modeldata',
            order_with_respect_to='name',
        ),
        migrations.CreateModel(
            name='syntheticdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthetic_data', models.FileField(blank=True, upload_to='documents/%Y/%m/%d', validators=[core.validators.validate_file_extension])),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modeldata')),
            ],
            options={
                'order_with_respect_to': 'name',
            },
        ),
    ]
